In [ ]:
a = [1,1,1,2,2,3,3,3]
print(a)
print(a.index(1))
del(a[a.index(1)])
print(a)

In [ ]:
c = [['00','01'],['10','11'],['20','21']]
print(c)
print(c[2][1])

In [ ]:
import numpy
a = numpy.zeros((3, 3))
print(a)
a[0][0] = 1
a[0][1] = 1
a[0][2] = 2
a[1][2] = 2
a[2][2] = 2
print(a)
print(a[:,2])



In [32]:
import numpy
#   0 = 0,0 -> 2,2 
#   1 = 0,3 -> 2,5 
#   2 = 0,6 -> 2,8
#   3 = 3,0 -> 5,2
#   4 = 3,3 -> 5,5
#   5 = 3,6 -> 5,8
#   6 = 6,0 -> 8,2
#   7 = 6,3 -> 8,5
#   8 = 6,6 -> 8,8
a = numpy.zeros((9, 9))
def sudoku_line(n, matrix):
    return matrix[n,:]
def sudoku_grid(n, matrix):
    xi = int(n/3) * 3
    yi = (n%3) * 3
    xf = xi + 2
    yf = yi + 2
    grid = [(xi) : (xf+1) , :(yf+1)].reshape(9)
    return grid

a[6,0] = 1
a[7,1] = 1
a[8,2] = 1
b = sudoku_grid(6,a)
print(b)


    

SyntaxError: invalid syntax (<ipython-input-32-cd2814b3c177>, line 19)

In [ ]:
a=[[ 1, 1,  3,],
 [ 4,  5,  6,],
 [ 6,  6,  9,]]


def sudoku_penality(array):
    p = 0
    for i in range (1,10):
        if not array.count(i):
            p += 1
    return p
print(c)
print(sudoku_penality(c))


In [28]:
import numpy

def sudoku_fixed(matrix):  
    fixed = numpy.zeros((9, 9))
    it = numpy.nditer(matrix, flags=['multi_index'])
    while not it.finished:
        if(it[0] > 0):
            fixed[it.multi_index[0],it.multi_index[1]] = 1
        it.iternext()
    return fixed
            
a = numpy.zeros((9, 9))
a[0][0] = 1
a[0][1] = 1
a[0][2] = 2
a[1][2] = 2
a[2][2] = 2
print(a)
print(a[0:3,:3])
b= a[0:3,:3].reshape(9)
print(b)


[[ 1.  1.  2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 1.  1.  2.]
 [ 0.  0.  2.]
 [ 0.  0.  2.]]
[ 1.  1.  2.  0.  0.  2.  0.  0.  2.]


In [ ]:
a = numpy.zeros((9, 9))
a[0][0] = 1
a[0][1] = 1
a[0][2] = 2
a[1][2] = 2
a[2][2] = 2
print(a)

In [ ]:
a = 2